# Generated by Django 3.0.3 on 2020-04-29 23:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=1024)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('length', models.IntegerField()),
                ('date_written', models.DateField(auto_now_add=True)),
                ('negative_words', models.IntegerField(null=True)),
                ('smarter_negative_words', models.IntegerField(null=True)),
                ('smarter_positive_words', models.IntegerField(null=True)),
                ('contents', models.TextField(null=True)),
                ('tokens', models.TextField(null=True)),
            ],
            options={
                'ordering': ['date_written'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ticker', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.IntegerField(choices=[('Ireland', 0), ('United Kingdom', 1), ('Unknown', None)], default=None)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(related_name='words', to='sentiment.Category')),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='WordsInArticleCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler.Article')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler.Word')),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('adj_close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('interday_volatility', models.FloatField()),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_handler.Asset')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler.Source'),
        ),
    ]
